# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: 3

dotenv:
  - .env

tasks:
  setup:cilium:
    cmds:
      - helm repo add cilium https://helm.cilium.io/
      - helm repo update
      - |
        helm upgrade --install cilium cilium/cilium \
          --namespace kube-system \
          -f bootstrap/cilium/values.yaml \
          --wait

  setup:tailscale:
    cmds:
      - helm repo add tailscale https://pkgs.tailscale.com/helmcharts
      - helm repo update
      - |
        helm upgrade --install tailscale-operator tailscale/tailscale-operator \
          --namespace=tailscale \
          --create-namespace \
          --set-string oauth.clientId=$TAILSCALE_CLIENT_ID \
          --set-string oauth.clientSecret=$TAILSCALE_CLIENT_SECRET \
          --wait

  setup:argocd:
    cmds:
      - helm repo add argo https://argoproj.github.io/argo-helm
      - helm repo update
      - |
        helm upgrade --install argocd argo/argo-cd \
          --namespace argocd \
          --create-namespace \
          -f bootstrap/argocd/values.yaml \
          --wait
      - kubectl apply -f bootstrap/argocd/root-app.yaml

  secret:cnpg:
    vars:
      PG_USER: postgres
      PG_PASSWORD:
        sh: openssl rand -base64 24
    cmds:
      - kubectl create namespace database --dry-run=client -o yaml | kubectl apply -f -
      - echo Generated password {{.PG_PASSWORD}}
      - |
        kubectl create secret generic cnpg-superuser-secret \
          --namespace database \
          --from-literal=username={{.PG_USER}} \
          --from-literal=password="{{.PG_PASSWORD}}" \
          --dry-run=client -o yaml | kubectl apply -f -

  secret:infisical:
    vars:
      DB_CLUSTER_NAME: postgres
      DB_POD:
        sh: kubectl get pod -n database -l cnpg.io/cluster={{.DB_CLUSTER_NAME}},cnpg.io/instanceRole=primary -o jsonpath='{.items[0].metadata.name}'
      DB_NAME: infisical
      DB_USER: infisical
      DB_PASSWORD:
        sh: openssl rand -hex 24
      AUTH_SECRET:
        sh: openssl rand -hex 32
      ENCRYPTION_KEY:
        sh: openssl rand -hex 16
    cmds:
      - |
        kubectl create secret generic infisical-secrets \
          --namespace infisical \
          --from-literal=DB_CONNECTION_URI="postgresql://{{.DB_USER}}:{{.DB_PASSWORD}}@{{.DB_CLUSTER_NAME}}-rw.database.svc:5432/{{.DB_NAME}}" \
          --from-literal=AUTH_SECRET="{{.AUTH_SECRET}}" \
          --from-literal=ENCRYPTION_KEY="{{.ENCRYPTION_KEY}}" \
          --from-literal=REDIS_URL="redis://redis-master.database.svc:6379" \
          --dry-run=client -o yaml | kubectl apply -f -
      - kubectl exec -n database -i {{.DB_POD}} -- psql -U postgres -c "CREATE USER {{.DB_USER}};" || true
      - kubectl exec -n database -i {{.DB_POD}} -- psql -U postgres -c "ALTER USER {{.DB_USER}} WITH ENCRYPTED PASSWORD '{{.DB_PASSWORD}}';" || echo "User likely exists, skipping..."
      - kubectl exec -n database -i {{.DB_POD}} -- psql -U postgres -c "CREATE DATABASE {{.DB_NAME}} OWNER {{.DB_USER}};" || echo "DB likely exists, skipping..."

  secret:cert-manager:
    cmds:
      - |
        kubectl create secret generic cloudflare-api-token \
          --namespace cert-manager \
          --from-literal=api-token=$CLOUDFLARE_API_TOKEN
