# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: 3

tasks:
  setup:traefik:
    cmds:
      - helm repo add traefik https://traefik.github.io/charts
      - helm repo update
      - |
        helm upgrade --install traefik traefik/traefik \
          --namespace kube-system \
          --create-namespace \
          -f bootstrap/traefik/values.yaml

  setup:argocd:
    cmds:
      - helm repo add argo https://argoproj.github.io/argo-helm
      - helm repo update
      - |
        helm upgrade --install argocd argo/argo-cd \
          --namespace argocd \
          --create-namespace \
          -f bootstrap/argocd/values.yaml \
          --wait
      # Apply the Root App manually to kickstart GitOps
      - kubectl apply -f bootstrap/argocd/root-app.yaml
