apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: private-gateway
  namespace: networking
spec:
  gatewayClassName: traefik
  listeners:
    {{- range .Values.gateways.private.listeners }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      {{- if .hostname }}
      hostname: {{ .hostname | quote }}
      {{- end }}
      allowedRoutes:
        namespaces:
          from: All
      {{- if eq .protocol "HTTPS" }}
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ .tlsSecret }}
      {{- end }}
    {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-private
  namespace: kube-system
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: {{ .Values.gateways.private.tailscaleHostname | quote }}
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app.kubernetes.io/name: traefik
  ports:
    - name: https
      port: 443
      targetPort: 8444
      protocol: TCP
