apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: private-gateway
  namespace: networking
spec:
  gatewayClassName: cilium-tailscale
  infrastructure:
    annotations:
      tailscale.com/expose: "true"
      tailscale.com/hostname: {{ .Values.gateways.private.tailscaleHostname | quote }}
  listeners:
    {{- range .Values.gateways.private.listeners }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      {{- if .hostname }}
      hostname: {{ .hostname | quote }}
      {{- end }}
      allowedRoutes:
        namespaces:
          from: All
      {{- if eq .protocol "HTTPS" }}
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ .tlsSecret }}
      {{- end }}
    {{- end }}
---
apiVersion: cilium.io/v2alpha1
kind: CiliumGatewayClassConfig
metadata:
  name: tailscale-config
  namespace: kube-system
spec:
  service:
    loadBalancerClass: tailscale
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: cilium-tailscale
spec:
  controllerName: io.cilium/gateway-controller
  parametersRef:
    group: cilium.io
    kind: CiliumGatewayClassConfig
    name: tailscale-config
    namespace: kube-system
