apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: public-gateway
  namespace: networking
spec:
  gatewayClassName: cilium
  listeners:
    {{- range .Values.gateways.public.listeners }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      {{- if .hostname }}
      hostname: {{ .hostname | quote }}
      {{- end }}
      allowedRoutes:
        namespaces:
          from: All
      {{- if eq .protocol "HTTPS" }}
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ .tlsSecret }}
      {{- end }}
    {{- end }}
