apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: public-gateway
  namespace: networking
spec:
  gatewayClassName: cilium-public
  listeners:
    {{- range .Values.gateways.public.listeners }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      {{- if .hostname }}
      hostname: {{ .hostname | quote }}
      {{- end }}
      allowedRoutes:
        namespaces:
          from: All
      {{- if eq .protocol "HTTPS" }}
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ .tlsSecret }}
      {{- end }}
    {{- end }}
---
apiVersion: cilium.io/v2alpha1
kind: CiliumGatewayClassConfig
metadata:
  name: cilium-public-config
  namespace: kube-system
spec:
  service:
    type: NodePort
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: cilium-public
spec:
  controllerName: io.cilium/gateway-controller
  parametersRef:
    group: cilium.io
    kind: CiliumGatewayClassConfig
    name: cilium-public-config
    namespace: kube-system
