{{- range .Values.certificates }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .domain | replace "." "-" }}-cert
  namespace: networking
spec:
  secretName: {{ .secretName }}
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  commonName: "*.{{ .domain }}"
  dnsNames:
    - "*.{{ .domain }}"
    - "{{ .domain }}"
---
{{- end }}
