apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: overburrow-wildcard
  namespace: networking
spec:
  secretName: overburrow-wildcard-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  commonName: "*.overburrow.dev"
  dnsNames:
    - "*.overburrow.dev"
    - "overburrow.dev"
